### PR TITLE
feat: I created a hyperlink

### LINKED ISSUE #19: the `<a>` tag

### PR DESCRIPTION
**Pull request by Alez05**
fix #19

### CODE REVIEW

**Review by marianzburlea — CHANGES_REQUESTED** [review]
add more examples

**Review by antonia2203 — APPROVED** [review]
wow

**Review by flivanov92 — APPROVED** [review]
👍

**Review by MariaTeo — CHANGES_REQUESTED** [review]
poti adauga si atributul title

**Review by Vivy — APPROVED** [review]
nice

**Review by MariaTeo — APPROVED** [review]
yay

**Review by marianzburlea — APPROVED** [review]
💯

**Pull request merged**
