### PR TITLE
add table tag examples

### LINKED ISSUE #17: the `<table>` tag, the `<tr>` tag, the `<td>` tag
More info about the **table** tag: https://www.w3schools.com/tags/tag_table.asp

### PR DESCRIPTION
**Pull request by marianzburlea**
fix #17

### CODE REVIEW

**Review by Alez05 — APPROVED** [review]
Great

**Review by antonia2203 — APPROVED** [review]
💯

**Review by MariaTeo — APPROVED** [review]
nice

**Review by Vivy — APPROVED** [review]
Very good info, Thanks

**Pull request merged**
